export const profileCopy = {
  tabTitle: 'Profil',
  screenTitle: 'Profil',
  fullName: 'Ad Soyad',
  email: 'E-posta',
  notifications: 'Bildirimler',
  notificationsHint: 'Her tarama sonrası yeni ilan özetleri.',
  scanFrequency: 'Tarama Sıklığı',
  scanFrequencyValue: 'Her 2 saatte bir',
  scanFrequencyHint: 'Sunucuda çalışır; telefonunuz kapalı olsa da devam eder.',
  cv: 'CV',
  cvEmpty: 'Henüz CV yüklenmedi.',
  favorites: 'Favoriler',
  favoritesHint: 'Kayıtlı ilanlar, arama sekmelerinden bağımsızdır.',
  signOut: 'Çıkış Yap',
  signingOut: 'Çıkış yapılıyor...',
  signOutTitle: 'JobRadar oturumu kapatılsın mı?',
  loadError: 'Profil yüklenemedi.',
  updateError: 'Bildirim tercihi güncellenemedi.',
  signedIn: 'Oturum açık',
  locationSection: 'Konum Bilgileri',
  country: 'Ülke',
  city: 'Şehir',
  countryPlaceholder: 'Türkiye',
  cityPlaceholder: 'İzmir',
  locationHint: 'Aramalarda konum belirtmezseniz bu konum kullanılır.',
  saveLocation: 'Kaydet',
  locationSaveError: 'Konum kaydedilemedi.',
  locationSaveRetry: 'Tekrar deneyin.',
  countryRequired: 'Ülke gerekli.',
  setupTitle: 'Konumunuzu belirleyin',
  setupSubtitle: 'Aramalarda konum belirtmediğinizde bu bilgi kullanılacak.',
  continue: 'Kaydet',
} as const;
