export const Colors = {
  light: {
    text: '#0F172A',
    textSecondary: '#64748B',
    background: '#F3F6FB',
    backgroundElement: '#FFFFFF',
    backgroundSelected: '#E8EEF8',
    border: '#E2E8F0',
    accent: '#2563EB',
    accentMuted: '#DBEAFE',
    secondary: '#7C3AED',
    secondaryMuted: '#EDE9FE',
    success: '#16A34A',
    successMuted: '#DCFCE7',
    warning: '#F59E0B',
    warningMuted: '#FEF3C7',
    danger: '#DC2626',
    dangerMuted: '#FEE2E2',
    overlay: 'rgba(15, 23, 42, 0.45)',
    onAccent: '#FFFFFF',
  },
  dark: {
    text: '#F8FAFC',
    textSecondary: '#94A3B8',
    background: '#0B1220',
    backgroundElement: '#151B2B',
    backgroundSelected: '#1E293B',
    border: '#243044',
    accent: '#3B82F6',
    accentMuted: '#1E3A5F',
    secondary: '#A78BFA',
    secondaryMuted: '#2E2158',
    success: '#22C55E',
    successMuted: '#14532D',
    warning: '#FBBF24',
    warningMuted: '#3F2E0A',
    danger: '#F87171',
    dangerMuted: '#4C1D1D',
    overlay: 'rgba(0, 0, 0, 0.55)',
    onAccent: '#FFFFFF',
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;
