export const authCopy = {
  brand: 'JobRadar',
  signInTitle: 'Giriş Yap',
  signInSubtitle: 'Devam etmek için e-posta adresinizi kullanın.',
  signIn: 'Giriş Yap',
  createAccountTitle: 'Hesap Oluştur',
  createAccountSubtitle: 'Tüm ilanlarınızı tek yerde toplamaya başlayın.',
  createAccount: 'Hesap Oluştur',
  name: 'Ad Soyad',
  email: 'E-posta',
  password: 'Şifre',
  namePlaceholder: 'Adınız',
  emailPlaceholder: 'ornek@eposta.com',
  passwordPlaceholder: 'En az 8 karakter',
  noAccount: 'Hesabınız yok mu? ',
  hasAccount: 'Zaten hesabınız var mı? ',
  confirmation: 'Hesabınızı onaylamak için e-postanızı kontrol edin, ardından giriş yapın.',
  nameRequired: 'Ad soyad gerekli.',
  emailInvalid: 'Geçerli bir e-posta adresi girin.',
  passwordMin: 'Şifre en az 8 karakter olmalı.',
  signInFailed: 'Giriş yapılamadı. Tekrar deneyin.',
  signInNetwork: 'Giriş yapılamadı. Bağlantınızı kontrol edip tekrar deneyin.',
  signUpFailed: 'Hesap oluşturulamadı. Tekrar deneyin.',
  signUpNetwork: 'Hesap oluşturulamadı. Bağlantınızı kontrol edip tekrar deneyin.',
  invalidCredentials: 'E-posta veya şifre hatalı.',
  emailNotConfirmed: 'Giriş yapmadan önce e-postanızı onaylayın.',
  alreadyRegistered: 'Bu e-posta ile bir hesap zaten var. Giriş yapın.',
  country: 'Ülke',
  city: 'Şehir',
  countryPlaceholder: 'Türkiye',
  cityPlaceholder: 'İzmir',
  countryRequired: 'Ülke gerekli.',
} as const;
